name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build 
      run: docker build -f flask/Dockerfile -t mlops:v12 .
        
    - name: Tag
      run: docker tag mlops:v12 onkar17/mlops:v12
      
    - name: Push
      run: docker push onkar17/mlops:v12
      
      

    
